settings:
  REFUND_CLAIM_BLOCKS: true
  CUSTOM_WORLD_NAMES:
    world: Dünya
  # claim süresinin maksimum ne kadara ulaşabileceğini belirler
  MAX_CLAIM_DAYS_BY_PERMISSION:
    perm: 60
    default: 30
  DAY_PRICE: 1000 # 1 gün uzatmak için gerekli ücret
  SETHOME_COMMANDS: ["sethome", "esethome", "createhome", "ecreatehome"]
gui:
  claim-menu:
    title: "<gray>Claim"
    FILLER: &filler
      ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
      material: BLACK_STAINED_GLASS_PANE
      name: "<gray> "
      lore: []
    OTHER:
      - ==: me.ahmetflix.claim.gui.item.ConfigItem
        slot: 9
        update: true
        identifier: claim-info
        item:
          ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
          material: BOOK
          name: "<color:#e8e850>Claim Bilgi"
          lore:
            - ""
            - "<color:#f3f3a0>Claim Genişliği <gray>▶ <color:#e8e850><size>"
            - "<color:#f3f3a0>Claim Koordinatları <gray>▶ <color:#e8e850>x: <x>, y: <y>, z: <z>"
            - "<color:#f3f3a0>Claim Süresi <gray>▶ <color:#e8e850><remaining>"
      - ==: me.ahmetflix.claim.gui.item.ConfigItem
        slot: 11
        update: false
        identifier: claim-time
        item:
          ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
          material: CLOCK
          name: "<color:#e8e850>Claim Süresi Uzatma"
          lore:
            - ""
            - "<color:#f3f3a0>Claim süreni uzatmak için <color:#e8e850><u>tıkla</u><color:#f3f3a0>!"
      - ==: me.ahmetflix.claim.gui.item.ConfigItem
        slot: 13
        update: false
        identifier: claim-list
        item:
          ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
          material: GRASS_BLOCK
          name: "<color:#e8e850>Claim Listesi"
          lore:
            - ""
            - "<color:#f3f3a0>Claimlerini görüntülemek için <color:#e8e850><u>tıkla</u><color:#f3f3a0>!"
      - ==: me.ahmetflix.claim.gui.item.ConfigItem
        slot: 15
        update: false
        identifier: claim-remove
        item:
          ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
          material: BARRIER
          name: "<color:#e8e850>Claim Sil"
          lore: []
      - ==: me.ahmetflix.claim.gui.item.ConfigItem
        slot: 17
        update: false
        identifier: claim-config
        item:
          ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
          material: SPYGLASS
          name: "<color:#e8e850>Claim Ayarları"
          lore: []
  claim-list:
    title: "<gray>Claim Listesi"
    CLAIM:
      ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
      material: GRASS_BLOCK
      name: "<color:#e8e850>Claimin"
      lore:
        - "<color:#f3f3a0>Lokasyon: <color:#e8e850>x: <x>, y: <y>, z: <z>"
        - "<color:#f3f3a0>Kalan Süre: <color:#e8e850><remaining>"
        - "<color:#f3f3a0>Bölge: <color:#e8e850><world>"
    PREVIOUS:
      ==: me.ahmetflix.claim.gui.item.ConfigItem
      slot: 18
      update: false
      identifier: previous
      item:
        ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
        material: ARROW
        name: "<color:#e8e850>Geri"
        lore: []
    NEXT:
      ==: me.ahmetflix.claim.gui.item.ConfigItem
      slot: 26
      update: false
      identifier: next
      item:
        ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
        material: ARROW
        name: "<color:#e8e850>İleri"
        lore: []
  claim-remove:
    title: "<gray>Claim Sil"
    FILLER: *filler
    BACK: &back
      ==: me.ahmetflix.claim.gui.item.ConfigItem
      slot: 26
      update: false
      identifier: back
      item:
        ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
        material: ARROW
        name: "<color:#e8e850>Geri"
        lore: [ ]
    VERIFY_REMOVAL:
      ==: me.ahmetflix.claim.gui.item.ConfigItem
      slot: 13
      update: false
      identifier: verify-removal
      item:
        ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
        material: TNT
        name: "                            <color:#e8e850><bold>DUR!</bold>"
        lore:
          - ""
          - "  <color:#f3f3a0>Claimini kaldırmaya emin misin?"
          - "<color:#f3f3a0>Onaylamak için <color:#e8e850><u>tıkla</u><color:#f3f3a0>!"
  claim-time:
    title: "<gray>Claim Süresi Uzatma"
    FILLER: *filler
    BACK: *back
    EXTEND_CONFIRM:
      ==: me.ahmetflix.claim.gui.item.ConfigItem
      slot: 4
      update: false
      identifier: extend-confirm
      item:
        ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
        material: BLAZE_ROD
        name: "<green>Onaylamak için tıkla<color:#f3f3a0>!"
        lore:
          - "<color:#f3f3a0>Toplam Fiyat <gray>▶ <color:#e8e850><price>"
          - "<color:#f3f3a0>Uzatılacak Gün <gray>▶ <color:#e8e850><day>"
    EXTEND_ADD_DAY:
      ==: me.ahmetflix.claim.gui.item.ConfigItem
      slot: 14
      update: false
      identifier: extend-add-day
      item:
        ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
        material: CLOCK
        name: "<color:#e8e850>1 Gün <color:#f3f3a0>Ekle"
        lore: []
    EXTEND_REMOVE_DAY:
      ==: me.ahmetflix.claim.gui.item.ConfigItem
      slot: 12
      update: false
      identifier: extend-remove-day
      item:
        ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
        material: COMPASS
        name: "<color:#e8e850>1 Gün <color:#f3f3a0>Azalt"
        lore: []
  claim-config:
    title: "<gray>Claim Ayarları"
    FILLER: *filler
    BACK: *back
    ANIMALS_ENABLED:
      ==: me.ahmetflix.claim.gui.item.ConfigItem
      slot: 11
      update: false
      identifier: animals-enabled
      item:
        ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
        material: CAT_SPAWN_EGG
        name: '<color:#f3f3a0>Hayvan Doğuşu: <color:#58D68D>✔'
        lore:
          - ""
          - "<color:#f3f3a0>Kapatmak için <color:#e8e850><u>tıkla</u><color:#f3f3a0>!"
    ANIMALS_DISABLED:
      ==: me.ahmetflix.claim.gui.item.ConfigItem
      slot: 11
      update: false
      identifier: animals-disabled
      item:
        ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
        material: COW_SPAWN_EGG
        name: '<color:#f3f3a0>Hayvan Doğuşu: <color:#EC7063>✘'
        lore:
          - ""
          - "<color:#f3f3a0>Açmak için <color:#e8e850><u>tıkla</u><color:#f3f3a0>!"
    MONSTERS_ENABLED:
      ==: me.ahmetflix.claim.gui.item.ConfigItem
      slot: 13
      update: false
      identifier: monters-enabled
      item:
        ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
        material: BLAZE_SPAWN_EGG
        name: '<color:#f3f3a0>Canavar Doğuşu: <color:#58D68D>✔'
        lore:
          - ""
          - "<color:#f3f3a0>Kapatmak için <color:#e8e850><u>tıkla</u><color:#f3f3a0>!"
    MONSTERS_DISABLED:
      ==: me.ahmetflix.claim.gui.item.ConfigItem
      slot: 13
      update: false
      identifier: monsters-disabled
      item:
        ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
        material: ENDERMAN_SPAWN_EGG
        name: '<color:#f3f3a0>Canavar Doğuşu: <color:#EC7063>✘'
        lore:
          - ""
          - "<color:#f3f3a0>Açmak için <color:#e8e850><u>tıkla</u><color:#f3f3a0>!"
    MEMBERS:
      ==: me.ahmetflix.claim.gui.item.ConfigItem
      slot: 15
      update: false
      identifier: members
      item:
        ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
        material: PLAYER_HEAD
        name: "<color:#e8e850>Üyeler"
        lore:
          - ""
          - "<color:#f3f3a0>Üyelerini görüntülemek için <color:#e8e850><u>tıkla</u><color:#f3f3a0>!"
  claim-config-playerlist:
    title: "<gray>Üyeler"
    PREVIOUS: #büyük ihtimalle görünmeyecek bile ama ne olur ne olmaz
      ==: me.ahmetflix.claim.gui.item.ConfigItem
      slot: 45
      update: false
      identifier: previous
      item:
        ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
        material: ARROW
        name: "<color:#e8e850>Geri"
        lore: [ ]
    NEXT: #büyük ihtimalle görünmeyecek bile ama ne olur ne olmaz
      ==: me.ahmetflix.claim.gui.item.ConfigItem
      slot: 53
      update: false
      identifier: next
      item:
        ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
        material: ARROW
        name: "<color:#e8e850>İleri"
        lore: [ ]
    BACK: &back2
      ==: me.ahmetflix.claim.gui.item.ConfigItem
      slot: 49
      update: false
      identifier: back
      item:
        ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
        material: ARROW
        name: "<color:#e8e850>Ayarlara Geri Dön"
        lore: []
    PLAYER: # eğer player_head ayarlarsanız oyuncunun kafası gözükür
      ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
      material: PLAYER_HEAD
      name: "<color:#e8e850><player>"
      lore: []
  claim-config-player:
    title: "<gray>Üye Ayarı (<player>)"
    BACK: *back2
    FLAG_ENABLED:
      ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
      material: LIME_STAINED_GLASS_PANE
      name: "<flag> <color:#58D68D>✔"
      lore:
        - ""
        - "<color:#f3f3a0>Kapatmak için <color:#e8e850><u>tıkla</u><color:#f3f3a0>!"
    FLAG_DISABLED:
      ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
      material: RED_STAINED_GLASS_PANE
      name: "<flag> <color:#EC7063>✘"
      lore:
          - ""
          - "<color:#f3f3a0>Açmak için <color:#e8e850><u>tıkla</u><color:#f3f3a0>!"
    PLAYER:
        ==: me.ahmetflix.claim.gui.item.ConfigItem
        slot: 4
        update: false
        identifier: player
        item:
          ==: me.ahmetflix.claim.gui.item.ConfigItem$ItemInfo
          material: PLAYER_HEAD
          name: "<color:#e8e850><player>"
          lore: []
    FILLER: *filler
    SLOTS:
      BUILD: 20
      BUILD_HOPPERS: 21
      BREAK_BEACON: 22
      BREAK_SPAWNER: 23
      PLACE_SPAWNER: 24
      PLACE_FLUID: 29
      PLACE_ENTITIES: 30
      USE_ROD_ON_ENTITIES: 31
      USE_DOORS: 32
      USE_SETHOME: 33
      OPEN_CONTAINERS: 39
      TRIGGER_REDSTONE: 41